# git commit -am "dev" && git push -qf && gh workflow run cache.yml -F urls=@urls1 -F sums=@sums1 -f cache=plichta-1

name: Create cache
on:
  workflow_dispatch:
    inputs:
      urls:
        required: true
      sums:
        required: true
      cache:
        required: true
jobs:
  caching:
    runs-on: ubuntu-latest
    steps:

      - name: Download
        run: |
          curl -Z --create-dirs --output-dir input $(echo ${{ inputs.urls }})

      - name: List files
        run: |
          stat -c "%10s %n" input/*

      - name: Check sums
        run: |
          b2sum -c <<< ${{ inputs.sums }}

      - name: Save cache
        # if: always()
        uses: actions/cache/save@v3
        with:
          path: input
          key: ${{ inputs.cache }}
