# git commit -am "dev" && git push -qf && gh workflow run cache.yml -F urls=@urls -F xxh=@xxh

name: Cache input
on:
  workflow_dispatch:
    inputs:
      urls:
        required: true
      xxh:
        required: true
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
        # run: curl -Z --create-dirs --output-dir input -K - <<< '${{ inputs.urls }}'

      - name: Download input
        if: always()
        run: |
          curl -K - << "EOF"
          ${{ inputs.urls }}EOF
          echo AAAAAAAAAAAA

      - name: Download input
        if: always()
        run: |
          curl -K <(printf '${{ inputs.urls }}')
          echo CCCCCCCCCC


      # - name: Check input
      #   run: |
      #     stat -c "%10s  %n" input/*
      #     xxhsum -c <<< ${{ inputs.xxh }}

      # - name: Cache save input
      #   if: always()
      #   uses: actions/cache/save@v3
      #   with:
      #     path: input
      #     key: input-005
