# git commit -am "dev" && git push -qf && gh workflow run cache.yml -f id=3f1836af-8589-3da4-eea4-8b7a06f9d6ae -F sums=@sums

name: Create cache
run-name: ${{ inputs.id }}
on:
  workflow_dispatch:
    inputs:
      id:
        description: sendbig transfer id
        required: true
      sums:
        required: true
jobs:
  create cache:
    runs-on: ubuntu-latest
    steps:

      - name: Download
        run: |
          curl \
          --parallel \
          --remote-header-name \
          --remote-name-all \
          --create-dirs \
          --output-dir 'input' \
          $(curl \
          --referer 'https://www.sendbig.com' \
          --header 'Content-Type: application/json' \
          --data '{identifier:"${{ inputs.id }}"}' | \
          'https://s1.sendbig.com/api/Archive/viewArchive' \
          jq -j '.data.files[] |
          "https://",
          .serverIdentifier,
          ".sendbig.com/api/Files/download/",
          .id,
          "/${{ inputs.id }}/20138 "')

      - name: List files
        working-directory: input
        run: |
          ls -Qs1

      - name: Check sums
        run: |
          b2sum -c << "EOF"
          ${{ inputs.sums }}EOF

      - name: Save cache
        uses: actions/cache/save@v3
        with:
          path: input
          key: ${{ inputs.id }}
