# git commit -am. && git push -qf && gh workflow run dbree.yml -f title="Nimzo-Semi-Tarrasch-1" -F urls=@dbree-aonode-urls

name: dbree
run-name: ${{ inputs.title }}
on:
  workflow_dispatch:
    inputs:
      title:
        required: true
      urls:
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      - name: Preparing
        run: |
          sudo snap install ngrok
          ngrok http --authtoken ${{ secrets.NGROK_AUTHTOKEN }} --log ngrok.log file://$PWD &
          mkdir zip
          cat << "EOF" > urls
          ${{ inputs.urls }}EOF
          sleep 5
          cat ngrok.log

      - name: Download
        run: aria2c --input-file=urls --dir=zip --force-sequential=true --split=8 --max-connection-per-server=8 --max-concurrent-downloads=1 --log=download.log --log-level=notice --file-allocation=falloc --show-console-readout=true --summary-interval=30 --download-result=full --disk-cache=1024M

      - name: Extracting
        working-directory: zip
        run: |
          7z e *001
          for file in *.7z; do
              7z l "$file"
              7z l -slt "$file"
          done

      - name: Wait
        run: |
          while :; do
            sleep 60;
            (( total++ ))
            echo "Sleeping $total minutes..."
          done
