# git commit -am. && git push -qf && gh workflow run dbree-to-sendbig.yml -F urls=@dbree-urls -f pass=Immortal -f title='1.e4! Tactical Repertoire for White with IM Tor Fredrik Kaasen'

name: dbree-to-sendbig
run-name: ${{ inputs.title }}
on:
  workflow_dispatch:
    inputs:
      title:
        required: true
      urls:
        required: true
      pass:
        required: false

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      - run: mkdir zip unzip

      - name: download from dbree
        working-directory: zip
        run: |
          pip install -q selenium

          cookies=$(python -c '
          from selenium import webdriver
          from selenium.webdriver.chrome.options import Options
          chrome_options = Options()
          chrome_options.add_argument("--headless")
          driver = webdriver.Chrome(options=chrome_options)
          driver.get("https://dbree.org/v/381638")
          import time; time.sleep(10)
          print(";".join("=".join((d["name"],d["value"])) for d in driver.get_cookies()))')

          while read url0; do

            unset url1 url2
            until [[ $url2 == https://www2* ]]; do
              until [[ -n $url1 ]]; do
                sleep 1
                url1=$(curl -qsb $cookies $url0 | grep -om1 "//dbree.org/d/[^']*")
              done
              url2=$(curl -qsb $cookies -w '%{redirect_url}' https:$url1)
            done

            aria2c --split=8 --max-connection-per-server=16 --file-allocation=falloc --show-console-readout=false --console-log-level=warn --summary-interval=0 --disk-cache=1024M "$url2" &

          done << "EOF"
          ${{ inputs.urls }}EOF
          wait


      - name: extracting
        run: |
          7z l zip/*001
          7z x -ounzip -p${{ inputs.pass }} zip/*001
          tree -sF unzip


      - name: upload to sendbig
        working-directory: unzip
        run: |
          [[ $(ls -1 | wc -l) == 1 ]] && for dir in *; do cd "$dir"; done
          for file in *; do
            [[ -d "$file" ]] && 7z a -r -sdel "$file".zip "$file"
          done
          tree -sF

          json='{"password":"","files":[{"blob":{"$path":""},"fileName":"${{ inputs.title }}","imageData":null,"uploadPercentage":0,"uploadedBytes":0,"chunksArray":[{}],"chunkSize":2147483648,"fileSize":1,"fileId":-1,"currentChunk":0,"progressNumber":100,"isProcessingFile":false,"sessionId":"","totalUploaded":0,"didFinishUploading":false,"fileType":"","chunkProgressArray":[{"totalUploadedOfChunk":0}],"uploadedChunkIndexes":[],"chunkIndexesToUpload":[0],"toBeUploaded":false,"uploading":false,"uploadedBytesArray":[],"currentUploadedBytes":0,"totalChunks":1,"listIndex":0}],"expiryDays":7,"maximumNumberOfDownloads":0,"deferDays":0,"archiveId":0,"shouldSendReminder":true,"emailReminderCount":2,"snap":false,"max":false}'

          read sessionId archiveId <<< $(curl -qs https://s1.sendbig.com/api/Files/negotiate --referer https://www.sendbig.com/ -H 'Authorization: Bearer ${{ secrets.SENDBIG }}' -H 'Content-Type: application/json' -d "$json" | jq -j '.data|"\(.sessionId) \(.files[0].archiveId)"')

          json=$(jq -c --arg sessionId $sessionId --arg archiveId $archiveId '.files[0].sessionId=$sessionId|.archiveId=($archiveId|tonumber)' <<< "$json")

          echo "sessionId: $sessionId archiveId: $archiveId"

          for file in *; do

            size=$(stat -c%s "$file")

            json=$(jq -c --arg file "$file" --arg size $size '.files[0].fileName=$file|.files[0].fileSize=($size|tonumber)' <<< "$json")

            read sid id <<< $(curl -qs https://s1.sendbig.com/api/Files/negotiate --referer https://www.sendbig.com/ -H 'Authorization: Bearer ${{ secrets.SENDBIG }}' -H 'Content-Type: application/json' -d "$json" | jq -j '.data.files[0]|"\(.serverIdentifier) \(.id)"')

            curl -qs https://"$sid".sendbig.com/api/Files/advancedStreamUpload --referer https://www.sendbig.com/ -H 'Authorization: Bearer ${{ secrets.SENDBIG }}' -F fileName="$file" -F totalChunks=1 -F chunkSize=2147483648 -F fileId=$id -F fileSize=$size -F fileType="" -F archivePassword="" -F sessionId=${{ inputs.sessionId }} -F uploadedChunkIndexesCSV="" -F currentChunk=0 -F chunkFile=@"$file" && echo "$file" &

          done
          wait
          echo "https://www.sendbig.com/view-files/?Id=$sessionId"
