# git commit -am. && git push -qf && gh workflow run dbree.yml -f title="Nimzo-Semi-Tarrasch-1" -F urls=@dbree-urls

name: dbree
run-name: ${{ inputs.title }}
on:
  workflow_dispatch:
    inputs:
      title:
        required: true
      urls:
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      - name: Preparing
        run: |
          sudo snap install ngrok
          ngrok http --authtoken ${{ secrets.NGROK_AUTHTOKEN }} --log ngrok.log file://$PWD &

          cat << "EOF" > dbree-urls
          ${{ inputs.urls }}EOF

          pip install -q selenium
          cat << "EOF" > get-cookies.py
          import time
          from selenium import webdriver
          from selenium.webdriver.chrome.options import Options
          chrome_options = Options()
          chrome_options.add_argument("--headless")
          driver = webdriver.Chrome(options=chrome_options)
          driver.get("https://dbree.org/v/381638")
          time.sleep(10)
          print(";".join(f'{d["name"]}={d["value"]}' for d in driver.get_cookies()))
          EOF

          mkdir zip
          cat ngrok.log

      - name: Download
        run: |
          set -x
          cookies=$(python get-cookies.py)
          while read url0; do
              until [[ -n "$url1" ]]; do
                  sleep 1
                  url1=$(curl -qsb $cookies $url0 | grep -om1 "//dbree.org/d/[^']*")
              done
              url2=$(curl -qsb $cookies -w '%{redirect_url}' https:$url1)
              until [[ $url2 == https://www2* ]]; do
                  sleep 1
                  until [[ -n "$url1" ]]; do
                      sleep 1
                      url1=$(curl -qsb $cookies $url0 | grep -om1 "//dbree.org/d/[^']*")
                  done
                  url1=$(curl -qsb $cookies $url0 | grep -om1 "//dbree.org/d/[^']*")
                  url2=$(curl -qsb $cookies -w '%{redirect_url}' https:$url1)
              done
              echo "$url2" >> process.log
              aria2c --dir=zip --split=8 --max-connection-per-server=16 --log=download.log --log-level=notice --file-allocation=falloc --show-console-readout=false --summary-interval=10 --disk-cache=1024M "$url2"
          done < dbree-urls

      - name: Extracting
        working-directory: zip
        run: |
          7z e *001
          for file in *.7z; do
              7z l "$file"
              7z l -slt "$file"
          done

      - name: Wait
        run: |
          while :; do
            sleep 60;
            (( total++ ))
            echo "Sleeping $total minutes..."
          done
