name: Chessable LTR Giri French - PROCESS
run-name: Full process x2
on: workflow_dispatch
jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      - name: Restore cache
        uses: actions/cache/restore@v3
        with:
          path: |
            input/*.mp4
            input/*.mkv
          key: 475acdf1-a121-054f-44f3-172632bd1adb
          enableCrossOsArchive: true
          fail-on-cache-miss: true

      - name: Install ffmpeg + mkvtoolnix
        run: |
          # Install ffmpeg + mkvtoolnix
          sig=/usr/share/keyrings/gpg-pub-moritzbunkus.gpg
          sudo curl -so $sig https://mkvtoolnix.download/gpg-pub-moritzbunkus.gpg
          echo deb [signed-by=$sig] https://mkvtoolnix.download/ubuntu jammy main | \
          sudo tee /etc/apt/sources.list.d/mkvtoolnix.download.list
          sudo add-apt-repository ppa:savoury1/ffmpeg4
          sudo add-apt-repository ppa:savoury1/ffmpeg5
          sudo apt-fast -qq update
          sudo apt-fast -qq install mkvtoolnix ffmpeg

      - name: Versions
        run: mkvmerge -V; ffmpeg -version

      - name: Preset
        working-directory: input
        run: |
          cat << "EOF" | tee preset
          vcodec=libx264
          preset=veryfast
          tune=animation
          x264opts=no-scenecut
          crf=25
          g=1800
          threads=1
          acodec=libopus
          ab=16k
          apply_phase_inv=0
          frame_duration=60
          application=voip
          cutoff=12000
          EOF

      - name: Make dirs
        run: mkdir -p output/info tmp

      - name: ffmpeg
        working-directory: input
        run: |
          for file in *.mp4; do
          echo ::group::"$file"

          duration=$(ffprobe -v 24 -show_entries format=duration -of csv=p=0 "$file")

          trim=11:$(jq -n $duration-9)
          crop=1072:1072:840
          scale=536:536:flags=sinc
          fps=fps=source_fps:start_time=0:eof_action=pass

          FFREPORT=file=%p-%t.log:level=32 \
          ffmpeg -y -hide_banner -nostdin -nostats -benchmark -i "$file" \
          -ss 8.5 -to $(jq -n $duration-7) \
          -vf trim=$trim,crop=$crop,scale=$scale,fps=$fps \
          -ac 1 -fpre preset \
          "../tmp/$(basename "$file" .mp4).mkv"

          echo ::endgroup::
          done

      - name: mkvmerge
        working-directory: tmp
        run: |
          for file in *.mkv; do
            mkvmerge "$file" -o "../output/$file"
          done

      - name: Archive logs
        working-directory: input
        run: |
          tar cJvvf ../output/info/logs.tar.xz *.log

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Chessable LTR Giri French
          path: output
          retention-days: 5

# git commit -am. && git push -qf && gh workflow run process.yml
