# git commit -am. && git push -qf && gh workflow run process.yml -f title='1.e4! Tactical Repertoire for White with IM Tor Fredrik Kaasen' -f id=a8fcf57b-c078-9efc-4cf0-0b50fb5655de

name: Process
run-name: 1.e4! Tactical Repertoire for White with IM Tor Fredrik Kaasen
on:
  workflow_dispatch:
    inputs:
      title:
        required: true
      id:
        required: true
jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      - name: Install
        run: |
          sudo add-apt-repository https://mkvtoolnix.download/ubuntu && \
          sudo add-apt-repository ppa:savoury1/ffmpeg4 && \
          sudo add-apt-repository ppa:savoury1/ffmpeg5 && \
          sudo apt-fast -yqq --allow-insecure-repositories update && \
          sudo apt-fast -yqq --allow-unauthenticated install mkvtoolnix ffmpeg &

      - name: Make dirs
        run: mkdir -p output/info tmp

      - name: Download
        run: |
          curl -qZJ --remote-name-all \
          $(curl -qs --referer https://www.sendbig.com \
          -H 'Content-Type: application/json' \
          -d '{identifier:"${{ inputs.id }}"}' \
          https://s1.sendbig.com/api/Archive/viewArchive | \
          jq -j '.data.files | sort_by(.fileSize) | reverse[] |
          "https://\(.serverIdentifier).sendbig.com/api/Files/download/\(.id)/${{ inputs.id }}/20138 "')

      # - name: Extract
      #   run: unrar e -v *.001

      - name: List files
        run: ls -Qs1

      - name: Preset
        run: |
          cat << "EOF" | tee preset
          vcodec=libx264
          preset=veryfast
          tune=animation
          x264opts=no-scenecut
          crf=25
          g=1800
          threads=1
          acodec=libopus
          ab=16k
          apply_phase_inv=0
          frame_duration=60
          application=voip
          cutoff=12000
          EOF

      - name: Versions
        run: |
          until type mkvmerge ffmpeg &> /dev/null; do sleep 1; done
          mkvmerge -V; ffmpeg -version

      - name: ffmpeg
        run: |
          for file in *.mp4; do
            echo ::group::"$file"
            duration=$(ffprobe -v 24 -show_entries format=duration -of csv=p=0 "$file")

            ss=9
            to=$(jq -n $duration-0)
            trim=11:$(jq -n $duration-2)
            crop=1072:1072:4:8:exact=1
            fps=fps=30:start_time=0:eof_action=pass
            scale=536:536:flags=sinc
            # t=20

            FFREPORT=file=%p-%t.log:level=32 \
            ffmpeg -y -hide_banner -nostdin -nostats -benchmark -i "$file" \
            -ss $ss -to $to ${t+-t $t}\
            -vf trim=$trim,crop=$crop,${scale+scale=$scale,}fps=$fps \
            -ac 1 -fpre preset \
            "tmp/${file%.*}.mkv"

            echo ::endgroup::
          done

      - name: mkvmerge
        working-directory: tmp
        run: |
          for file in *.mkv; do
            echo ::group::"$file"
            mkvmerge "$file" -o "../output/$file"
            echo ::endgroup::
          done

      - name: Archive logs
        run: tar cJvvf output/info/logs.txz *.log

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.title }}
          path: output
          retention-days: 1
