# git ffmpeg-commit && git ffmpeg-push; gh ffmpeg-wrun script.yml -F script=@ -F data=@- -f title="" -f matrix=true

name: script
run-name: ${{ inputs.title || ( inputs.json && fromJSON(inputs.data).title) }}
on:
  workflow_dispatch:
    inputs:
      matrix:
        type: boolean
        default: false
      json:
        type: boolean
        default: false
      data:
        required: false
      data2:
        required: false
      remote:
        required: false
      script:
        required: true
      title:
        required: false
      cache:
        type: boolean
        default: true
env:
  path: /home/runner/.local/bin

jobs:

  script:
    if: ${{ ! inputs.matrix }}
    runs-on: ubuntu-latest
    env:
      data: ${{ inputs.json && fromJSON(inputs.data).data || inputs.data }}
      data2: ${{ inputs.json && fromJSON(inputs.data).data2 || inputs.data2 }}
      remote: ${{ inputs.remote }}
    steps:
      - if: inputs.cache
        uses: actions/cache/restore@v4
        with:
          key: bin
          path: ${{ env.path }}

      - name: Script
        run: |
          # script
          ${{ inputs.script }}


  script-matrix:
    if: inputs.matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        data: ${{ fromJson(inputs.data) }}
    env:
      data: ${{ matrix.data }}
      data2: ${{ inputs.data2 }}
    steps:
      - if: inputs.cache
        uses: actions/cache/restore@v4
        with:
          key: bin
          path: ${{ env.path }}

      - name: Script
        run: |
          # script
          ${{ inputs.script }}

