# git ffmpeg-commit && git ffmpeg-push; gh ffmpeg-wrun script.yml -F script=@ -F data=@- -f title="" -f matrix=true

name: script
run-name: ${{ inputs.title }}
on:
  workflow_dispatch:
    inputs:
      matrix:
        type: boolean
        default: false
      data:
        required: false
      data2:
        required: false
      remote:
        required: false
      script:
        required: true
      title:
        required: false
      cache:
        type: boolean
        default: true

jobs:

  script-matrix:
    if: inputs.matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        data: ${{ fromJson(inputs.data) }}
    env:
      data: ${{ matrix.data }}
      data2: ${{ inputs.data2 }}
    steps:

      - if: inputs.cache
        name: Sudo tar
        run: sudo chown root /usr/bin/tar && sudo chmod u+s $_

      - if: inputs.cache
        uses: actions/cache/restore@v4
        with:
          key: bin
          path: |
            /home/runner/.local/bin
            /lib/x86_64-linux-gnu/libfuse.*

      - name: Script
        run: |
          # script
          ${{ inputs.script }}


  script:
    if: ${{ ! inputs.matrix }}
    runs-on: ubuntu-latest
    env:
      data: ${{ inputs.data }}
      data2: ${{ inputs.data2 }}
      remote: ${{ inputs.remote }}
    steps:

      - if: inputs.cache
        name: Sudo tar
        run: sudo chown root /usr/bin/tar && sudo chmod u+s $_

      - if: inputs.cache
        uses: actions/cache/restore@v4
        with:
          key: bin
          path: |
            /home/runner/.local/bin
            /lib/x86_64-linux-gnu/libfuse.*

      - name: Script
        run: |
          # script
          ${{ inputs.script }}
