# git commit -am "dev" && git push -qf && gh workflow run test-install.yml

name: Install
run-name: Install ffmpeg and mkvtoolnix
on: workflow_dispatch
jobs:
  call-install:
    uses: ./.github/workflows/install.yml
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: ffprobe -version
