# git commit -am. && git push -qf && gh workflow run test.yml

name: Test
run-name: Test cache
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30
  job2:
    runs-on: ubuntu-latest
    steps:
      - needs: job1
        run: echo Ready

