# git commit -am. && git push -qf && gh workflow run test.yml

name: Test
run-name: Test ngrok
on: workflow_dispatch
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Ngrok
        run: |
          sudo snap install ngrok
          ngrok http --authtoken ${{ secrets.NGROK_AUTHTOKEN }} file:///.

      - name: Test
        run: |
          echo Test123 > test.txt
          while :; do sleep 10; done

